apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    devEnvApprovers:
    - todo
    clusterName: tf-jx-included-toad
    environmentGitOwner: osstap1989
    provider: eks
    region: eu-central-1
  environments:
  - key: dev
  - key: staging
  - key: production
  ingress:
    domain: "jekinsx.t1ddevelopment.org"
    externalDNS: true
    ignoreLoadBalancer: true
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  repository: nexus
  secretStorage: local
  vault: {}
  webhook: lighthouse
